<?php

declare(strict_types=1);

namespace Semitexa\PlatformUi\Attribute;

use Attribute;
use Semitexa\Core\Attribute\Capability;
use Semitexa\PlatformUi\Domain\Model\Contract\UiContract;
use Semitexa\PlatformUi\Domain\Model\Contract\UiExample;
use Semitexa\PlatformUi\Domain\Model\Contract\UiProp;

/** Opt-in authoring metadata; the existing component/primitive discovery owns identity. */
#[Capability(
    id: 'ui.contract',
    summary: 'Declares what a component or primitive accepts — summary, typed props, worked examples — so the catalog can describe it without anyone opening its template.',
    useWhen: 'A component is meant to be configured, previewed or generated by someone who did not write it, human or AI.',
    avoidWhen: 'You are registering the thing itself — identity stays with #[AsComponent] / #[AsUiPrimitive]; this only adds description.',
    replaces: [
        'prose documentation that drifts from the template it describes',
        'reading the Twig to guess which props exist and what values they take',
    ],
    seeAlso: 'ui.primitive',
)]
#[Attribute(Attribute::TARGET_CLASS)]
final readonly class AsUiContract
{
    /**
     * @param list<UiProp> $props
     * @param list<UiExample> $examples
     */
    public function __construct(
        public string $summary,
        public array $props = [],
        public array $examples = [],
        public bool $previewSafe = false,
    ) {}

    public function metadata(): UiContract
    {
        return new UiContract($this->summary, $this->props, $this->examples, $this->previewSafe);
    }
}
