<?php

declare(strict_types=1);

namespace Semitexa\PlatformUi\Application\Service\Icon;

/**
 * The icon registry — the full Lucide set (ISC, resources/icons/lucide/,
 * regenerated by `platform-ui:icons:sync`) rendered as inline SVG
 * (currentColor, so a glyph inherits text colour and scales with font size).
 * SSR-first: `icon('menu')` emits the SVG directly — no sprite, no request, and
 * only the icons a page uses ever reach it.
 *
 * Lookups are lazy: an old or alternative name resolves through aliases.json
 * (`home` → `house`), then only the shard for its first letter is read, once
 * per worker. Extend at runtime with add().
 */
final class IconRegistry
{
    private const NAME_PATTERN = '/\A[a-z0-9]+(?:-[a-z0-9]+)*\z/';

    /** @var array<string, array<string, string>> first char → shard (worker-lifetime cache) */
    private static array $shards = [];

    /** @var array<string, string>|null alias → canonical */
    private static ?array $aliases = null;

    /** @var array<string, string> runtime additions (win over the vendored set) */
    private static array $extra = [];

    public static function get(string $name): ?string
    {
        if (isset(self::$extra[$name])) {
            return self::$extra[$name];
        }
        if (preg_match(self::NAME_PATTERN, $name) !== 1) {
            return null;
        }
        $canonical = self::aliases()[$name] ?? $name;

        return self::shard($canonical[0])[$canonical] ?? null;
    }

    public static function has(string $name): bool
    {
        return self::get($name) !== null;
    }

    /**
     * Every canonical icon name (reads every shard — for catalogs and pickers,
     * not for page renders).
     *
     * @return list<string>
     */
    public static function names(): array
    {
        $names = array_keys(self::$extra);
        foreach (glob(self::directory() . '/?.json') ?: [] as $file) {
            array_push($names, ...array_keys(self::shard(basename($file, '.json'))));
        }
        $names = array_values(array_unique($names));
        sort($names);

        return $names;
    }

    /**
     * Search keywords per canonical name (Lucide's tags).
     *
     * @return array<string, list<string>>
     */
    public static function keywords(): array
    {
        $tags = json_decode((string) @file_get_contents(self::directory() . '/tags.json'), true);

        return is_array($tags) ? $tags : [];
    }

    /** @return array<string, string> */
    private static function shard(string $char): array
    {
        if (!isset(self::$shards[$char])) {
            $data = preg_match('/\A[a-z0-9]\z/', $char) === 1
                ? json_decode((string) @file_get_contents(self::directory() . '/' . $char . '.json'), true)
                : null;
            self::$shards[$char] = is_array($data) ? $data : [];
        }

        return self::$shards[$char];
    }

    /** @return array<string, string> */
    private static function aliases(): array
    {
        if (self::$aliases === null) {
            $data = json_decode((string) @file_get_contents(self::directory() . '/aliases.json'), true);
            self::$aliases = is_array($data) ? $data : [];
        }

        return self::$aliases;
    }

    private static function directory(): string
    {
        return dirname(__DIR__, 4) . '/resources/icons/lucide';
    }

    /** Add (or override) an icon at runtime — its inner SVG markup. */
    public static function add(string $name, string $innerSvg): void
    {
        self::$extra[$name] = $innerSvg;
    }

    /**
     * Render the named icon as inline SVG, or '' if unknown. A `label` makes it
     * an accessible image (role=img + aria-label); otherwise it is decorative
     * (aria-hidden). `size` is a px number or any CSS length; the icon uses
     * currentColor.
     *
     * @param array{size?: int|string, class?: string, label?: ?string, strokeWidth?: int|float} $opts
     */
    public static function render(string $name, array $opts = []): string
    {
        $inner = self::get($name);
        if ($inner === null) {
            return '';
        }

        $size = $opts['size'] ?? 24;
        $sizeAttr = is_int($size) ? (string) $size : (string) $size;
        $class = trim('sx-icon ' . (string) ($opts['class'] ?? ''));
        $strokeWidth = (string) ($opts['strokeWidth'] ?? 2);
        $label = $opts['label'] ?? null;

        $a11y = ($label !== null && trim((string) $label) !== '')
            ? sprintf('role="img" aria-label="%s"', htmlspecialchars((string) $label, ENT_QUOTES))
            : 'aria-hidden="true" focusable="false"';

        return sprintf(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="%s" height="%s" fill="none" stroke="currentColor" stroke-width="%s" stroke-linecap="round" stroke-linejoin="round" class="%s" %s>%s</svg>',
            htmlspecialchars($sizeAttr, ENT_QUOTES),
            htmlspecialchars($sizeAttr, ENT_QUOTES),
            htmlspecialchars($strokeWidth, ENT_QUOTES),
            htmlspecialchars(trim($class), ENT_QUOTES),
            $a11y,
            $inner,
        );
    }
}
