<?php

declare(strict_types=1);

namespace Semitexa\PlatformUi\Domain\Model\Event;

use Semitexa\PlatformUi\Domain\Model\Component\UiValuePath;

/**
 * Immutable event object passed to a component's #[UiOn] handler when the
 * UiInteractionDispatcher invokes it.
 *
 * Identity (componentName, instanceId, partName, eventName, updatesPath)
 * comes *only* from the SignedContext claims — never from the request body.
 * The dispatcher fails closed if signed claims and registry metadata
 * disagree, so by the time a handler receives this DTO every identity
 * field is authoritative.
 *
 * `$dispatchId` is a per-attempt identifier generated by the frontend
 * transport. The dispatcher already claimed it through the replay store
 * before the event reached the handler — handlers may surface it in
 * `debug` for correlation but MUST NOT use it for routing or trust.
 *
 * `$payload` is the client-supplied payload after the forbidden-field
 * guard has scrubbed it of any routing-flavored keys. It still contains
 * arbitrary user-controlled data — handlers must treat it accordingly.
 */
final readonly class UiInteractionEvent
{
    public function __construct(
        public string $componentName,
        public string $instanceId,
        public string $partName,
        public string $eventName,
        public ?UiValuePath $updatesPath,
        /** @var array<string, mixed> */
        public array $payload,
        public int $issuedAt,
        public int $expiresAt,
        /**
         * Raw signed-context claims map. Server-side only. The dispatcher
         * surfaces it so handlers can inspect TTL/iat without re-decoding.
         *
         * @var array<string, mixed>
         */
        public array $claims = [],
        public string $dispatchId = '',
        /**
         * Server-trusted per-event configuration carried in the signed
         * ctx's `cfg` claim. Populated at render time by the component
         * (e.g. FieldComponent passes validation rule specs here). The
         * dispatcher copies this out of the verified claims so handlers
         * read it as an authentic value.
         *
         * Handlers MUST NOT merge `$payload` data into config decisions
         * — payload is client-controlled, config is server-authored.
         *
         * @var array<string, mixed>
         */
        public array $config = [],
        /**
         * Client-submitted form value snapshot, sanitised by
         * UiFormPayloadSnapshot at the dispatch boundary. Keys are
         * safe identifiers; values are scalar or null.
         *
         * Trust boundary: this is **UX-feedback data only**. Cross-field
         * rules consult it through UiFieldValidationContext so a user
         * sees a coherent message while typing. The final-submit
         * pipeline (future slice) must revalidate against authoritative
         * state before persisting anything. Never treat snapshot
         * values as final business truth.
         *
         * @var array<string, scalar|null>
         */
        public array $formValues = [],
    ) {}

    /**
     * Convenience accessor for the most common case: a primitive that
     * carries a `value` (input/select/textarea). Returns null when the
     * payload has no `value` key.
     */
    public function value(): mixed
    {
        return $this->payload['value'] ?? null;
    }

    /**
     * Returns the validation rule spec list embedded in the signed
     * config under the compact `r` key. Always returns a list (empty
     * when no rules were signed).
     *
     * @return list<array<string, mixed>>
     */
    public function rules(): array
    {
        $rules = $this->config['r'] ?? null;
        if (!is_array($rules) || !array_is_list($rules)) {
            return [];
        }
        /** @var list<array<string, mixed>> $rules */
        return $rules;
    }
}
